name: store_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  # Firebase
  firebase_core: ^3.1.0

 
  connectivity_plus: ^5.0.2
  flutter_dotenv: ^5.1.0
  flutter_screenutil: ^5.9.3
  flutter_native_splash: ^2.4.0
  flutter_localizations:
    sdk: flutter
  
  # UI
  animate_do: ^3.3.4
  fluttertoast: ^8.2.5
  flutter_zoom_drawer: ^3.2.0
  shimmer: ^3.0.0



  # Bloc
  flutter_bloc: ^8.1.5
  # DataBase
  shared_preferences: ^2.2.3
  # Frezzed Code Generator
  freezed: ^2.5.2
  freezed_annotation: ^2.4.1
  # Code Generation  
  build_runner: ^2.4.9
  # dependency injection
  get_it: ^7.7.0

  # -------------API-------------
  # networking package
  dio: ^5.4.3+1
  # is a Dio interceptor that logs
  pretty_dio_logger: ^1.3.1
  # Automatically generate code for converting to and from JSON by annotating
  json_serializable: ^6.8.0
  # helper functions that support JSON code generation via the `json_serializable` package.
  json_annotation: ^4.9.0
  # is an dio client generator using source_gen 
  retrofit: ^4.1.0
  retrofit_generator: ^8.1.0
  # A Plugin for selecting images from the Android and iOS
  image_picker: ^1.1.2
  # This plugin provides a cross-platform (iOS, Android) API to request and check permissions.
  permission_handler: ^11.3.1
  cached_network_image: ^3.3.1
  fancy_shimmer_image: ^2.0.3
  delightful_toast: ^1.1.0

  # Notifcation
  firebase_messaging: ^15.0.1
  googleapis: ^13.2.0
  googleapis_auth: ^1.6.0
  # Local Database
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.19.0
  flutter_svg: ^2.0.10+1
  flutter_animate: ^4.5.0
  webview_flutter: ^4.8.0
  package_info_plus: ^8.0.0
  carousel_slider: ^4.2.1
  equatable: ^2.0.5
  bloc_concurrency: ^0.2.5
  firebase_dynamic_links: ^6.0.2
  share_plus: ^9.0.0
  flutter_local_notifications: ^17.1.2
  badges: ^3.1.2
  cloud_firestore: ^5.0.2
  
 

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.2
  # Extension for Hive. Automatically generates TypeAdapters to store any class.
  hive_generator: ^2.0.1
  


  very_good_analysis: ^5.1.0
  flutter_launcher_icons: ^0.13.1
flutter_launcher_icons:
  image_path: "assets/images/icons/app_icon.jpg"
  android: true
  ios: true
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/icons/play_store_512.png"
 

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - .env.dev
    - .env.prod
    - assets/images/core/
    - assets/icons/
    - assets/images/admin/
    - assets/images/customer/
    - assets/svg/
    - lang/




  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/arabic/cairo/Cairo-Bold.ttf
          weight: 700
        - asset: assets/fonts/arabic/cairo/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/arabic/cairo/Cairo-Regular.ttf
          weight: 400
    - family: Poppins
      fonts:
        - asset: assets/fonts/english/poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/english/poppins/Poppins-Medium.ttf  
          weight: 500
        - asset: assets/fonts/english/poppins/Poppins-Regular.ttf
          weight: 400
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
