// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbxitzEU-3rTvkcX4fJZkVIAndL5sebmE',
    appId: '1:370471112803:web:06a0ac42b00c64767b2856',
    messagingSenderId: '370471112803',
    projectId: 'flutterfirebase-2f227',
    authDomain: 'flutterfirebase-2f227.firebaseapp.com',
    storageBucket: 'flutterfirebase-2f227.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmdpRQ_Mr_l8dfnYl-1PfDScyt_dXWhoE',
    appId: '1:370471112803:android:66c6413ff8700f427b2856',
    messagingSenderId: '370471112803',
    projectId: 'flutterfirebase-2f227',
    storageBucket: 'flutterfirebase-2f227.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhN125s_dCJaTXjdHaKbuq_gKCAz1xwZs',
    appId: '1:370471112803:ios:45da626caf99e2c87b2856',
    messagingSenderId: '370471112803',
    projectId: 'flutterfirebase-2f227',
    storageBucket: 'flutterfirebase-2f227.appspot.com',
    androidClientId: '370471112803-sjk7podiv5tf63gmvtbheq1g5bu49jcq.apps.googleusercontent.com',
    iosBundleId: 'com.example.storeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhN125s_dCJaTXjdHaKbuq_gKCAz1xwZs',
    appId: '1:370471112803:ios:338fe5081e7bb7e97b2856',
    messagingSenderId: '370471112803',
    projectId: 'flutterfirebase-2f227',
    storageBucket: 'flutterfirebase-2f227.appspot.com',
    androidClientId: '370471112803-sjk7podiv5tf63gmvtbheq1g5bu49jcq.apps.googleusercontent.com',
    iosBundleId: 'com.example.storeApp.RunnerTests',
  );
}
