// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBno9QlNjJIeArMz0kLAq4D-m5WH_aILCs',
    appId: '1:810367351225:web:e8522606c58e2279cbde68',
    messagingSenderId: '810367351225',
    projectId: 'store-1cff8',
    authDomain: 'store-1cff8.firebaseapp.com',
    storageBucket: 'store-1cff8.appspot.com',
    measurementId: 'G-D8NMZWXM61',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDb7gy26_ayY-6xOgj_JJGy8_ErlZaOZmo',
    appId: '1:810367351225:android:a3d33e9e069e4f31cbde68',
    messagingSenderId: '810367351225',
    projectId: 'store-1cff8',
    storageBucket: 'store-1cff8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMkDyLEmoptdGRZj7vhmbKNSXq4IfSO2w',
    appId: '1:810367351225:ios:d33fdd16e5c91059cbde68',
    messagingSenderId: '810367351225',
    projectId: 'store-1cff8',
    storageBucket: 'store-1cff8.appspot.com',
    iosBundleId: 'com.example.storeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMkDyLEmoptdGRZj7vhmbKNSXq4IfSO2w',
    appId: '1:810367351225:ios:bf7fb20598bc8453cbde68',
    messagingSenderId: '810367351225',
    projectId: 'store-1cff8',
    storageBucket: 'store-1cff8.appspot.com',
    iosBundleId: 'com.example.storeApp.RunnerTests',
  );
}
